### ISSUE TITLE
Configure Sprite URL

### ISSUE THREAD

**Issue by tiagoferreira-mindera** [jkphl/grunt-svg-sprite#64]
Hi guys,

I have the following path schema:

- /styles/core.less  (here im importing sprite.less)
- /styles/spritesheet/css/sprite.less
- /styles/spritesheet/css/svg/sprite.css.svg

However inside sprite.less i have this: 

```less
.svg {
    background-image:url(svg/sprite.css.svg);
    background-repeat:no-repeat
}
```

And this not work because background image path can't be 'svg/sprite'. Instead should be '/spritesheet/css/svg/sprite.css.svg'.

How can i configure the configs on svg sprite to generate less files with this url guys?

Regards
